// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/724ceafbde3450d4afb3797c6c73141e862e75e0/react-ga/react-ga.d.ts
declare namespace __reactGA {
    export interface EventArgs {
        category: string;
        action: string;
        label?: string;
        value?: number;
        nonInteraction?: boolean;
    }

    export interface InitializeOptions {
        debug?: boolean;
    }

    export interface FieldsObject {
        [i: string]: any;
    }

    export function initialize(trackingCode: string, options?: InitializeOptions): void;
    export function pageview(path: string): void;
    export function modalview(name: string): void;
    export function event(args: EventArgs): void;
    export function set(fieldsObject: FieldsObject): void;
}

declare module 'react-ga' {
    export = __reactGA;
}
